# Generated by Django 3.2.3 on 2021-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.SmallIntegerField(choices=[(1, 'Windows'), (2, 'Mac'), (3, 'iPhone'), (4, 'Android'), (5, 'Other')], default=5)),
            ],
        ),
    ]
